apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wszn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wszn
    app.kubernetes.io/part-of: tkwch-fix-0075-0055-app
  name: devfile-sample-wszn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wszn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wszn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0055-tenant/tkwch-fix-0075-0055-app/devfile-sample-wszn@sha256:9a2d054cbe91c06b4972667411fdb6ab27194b477be15d1132e073f2f2f299f5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
